### ISSUE TITLE
"install" button is disabled for some packages

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#369] opened 2021-09-01 10:41 UTC
For example:

https://constructs.dev/packages/@softchef/cdk-schedule-function/v/0.0.55?lang=python

**Comment by Chriscbr** [comment] 2021-09-01 17:36
For me it shows that this package does not support Python, and the button says "Unsupported" - which I think is expected behavior. Does this still happen if you clear your cache?

**Comment by gabewomble** [comment] 2021-09-01 22:32
+1 @Chriscbr this is expected behavior when a user hits a url with a language that isn't supported. I think we can close this as it's not a bug, is that ok @addihorowitz?

**Closed** 2021-09-02 19:19 UTC
Labels: bug
