### ISSUE TITLE
List the tag indications for each package

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#323] opened 2021-08-09 14:03 UTC
Display the tag indications as keywords, but give them higher priority in their sorting over keywords

**Comment by MrArnoldPalmer** [comment] 2021-08-16 14:46
duplicate of https://github.com/cdklabs/construct-hub/issues/280 as no backend work is required.

**Closed by MrArnoldPalmer** 2021-08-16 14:46 UTC
