### ISSUE TITLE
Author badges: Community, AWS, HashiCorp and DataDog

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#580] opened 2021-11-04 14:41 UTC
The author badge in the package card and package page should be changed to:
'Community', 'AWS', 'DataDog' and 'Hashicorp'
The same labels should be used in the search results for filtering.

This task requires reprocessing packages on the backend to get these tags.
It also requires to add the AWS the new 65 packages from CFN registry.

Make sure the badge will be displayed on the package page. Not only on the package card.

**Comment by gabewomble** [comment] 2021-11-16 18:32
Duplicate of #639?

**Comment by Chriscbr** [comment] 2021-11-16 19:55
I'll mark this one as closed since the packages have now been processed, only the tag needs to be added to package card pages now.

**Closed by Chriscbr** 2021-11-16 19:55 UTC
Labels: priority/p0
